### PR TITLE
allow SNI in tls connection

### PR DESCRIPTION
**Pull request by hkjeffchan**
https://github.com/nodejs/node/issues/28167

### CODE REVIEW

**Comment by brettz9** [comment]
Thanks for the feature!

**Comment by brettz9** [comment]
Btw, we could really use some help getting our tests working fully again if you feel inspired and able to offer any help there.

**Comment by hkjeffchan** [comment]
Would you release this as v0.7.1? Thanks!

**Comment by brettz9** [comment]
Released as 0.8.0 (as it is a new feature, not a bug)

**Pull request merged**
